title: Distribution Governance
description: Legal & operational framework for a multi-member distribution venture in PA & NJ
baseurl: ""
url: "https://distribution-governance.github.io"

markdown: kramdown
theme: null

defaults:
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
  - prompt.md
